dist: 'trusty'

env:
  global:
    - ANSIBLE_FORCE_COLOR: True
    - ANSIBLE_LOG_PATH: './ansible.log'
    - ANSIBLE_ROLES_PATH: '../'

language: 'python'

python:
  - '2.7'

sudo: 'required'


install:
  # Install test requirements
  - 'pip install -r requirements-devel.txt'
  - 'scripts/install-ansible.sh'

script:
  # Check syntax of YAML files.
  - 'yamllint -c .yamllint.conf .'

  # Check syntax of role.
  - 'ansible-playbook -i localhost, -c local playbooks/allinone/midonet-allinone.yml --syntax-check'

  # Run role.
  - 'ansible-playbook -i localhost, -c local playbooks/allinone/midonet-allinone.yml --diff --verbose'

  # Run role again to check idempotence failure. TODO: Fix idempotency
  # - 'ansible-playbook -i localhost, -c local tests/test.yml --diff --verbose'

  # Detect idempotence failure.  TODO: Fix idempotency
  # - 'tail -n 5 ansible.log | grep -Eq "changed=0 +unreachable=0 +failed=0"'
  - sudo source /root/keystonerc_demo
  - openstack server list
  - openstack network list
  - openstack image list
